### ISSUE TITLE
Can't run the tool

### ISSUE THREAD

**Issue by Jojiv2** [falkensmz/tw1tter0s1nt#2]
![image](https://user-images.githubusercontent.com/76626446/168863925-535bd0b1-f81f-43ba-8d29-1b8ce0094750.png)

there is a problem with twint lib
btw i cant install twint

**Comment by falkensmz** [comment]
Have you installed the requirements for the tool? (pip3 install -r requirements.txt) If you have done that and it's still giving this "No module named 'twint' " error, please try to go through the twint installation manually. Steps have been provided on my repository. If you still cannot install twint, please go to their official page -> https://github.com/twintproject/twint ; and report any issue you may have there. By the way, sometimes you need to wait a few hours for the installation to fully complete and for twint to be fully compatible with your system, or just a quick reboot should do the trick. Thanks for reporting.

**Comment by Jojiv2** [comment]
i have reported it already, there is a problem in a module in the requirements file
